---
title: "Investigate bsa differences"
author: "Christelle Colin-Leitzinger"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: flatly
    highlight: pygments
    df_print: paged
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.figure {
   margin-top: 25px;
   margin-bottom: 100px;
}

table {
    margin-top: 1px;
    margin-bottom: 25px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```
<br>

## Investigate bsa differences

***

```{r library, include=FALSE}
library(drake)
library(tidyverse)
library(data.table)
library(lubridate)
library(ggplot2)
library(gtsummary)
library(survminer)
library(survival)
library(mice)
```

```{r loadd}
loadd(drugs)
creatinine <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/creatinine.rds")
weight <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/weight.rds")
height <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/height.rds")
body_surface_area <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/body_surface_area.rds")
areaUC <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/areaUC.rds")
clinical_data <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/clinical_data.rds")
Frontline <- read_rds("/Users/colinccm/Documents/GitHub/Peres/Treatment_Flatiron/Frontline.rds")
```

```{r}

```



```{r drugs episode cleanup}
drugs <- drugs %>% 
  `colnames<-`(str_to_lower(colnames(.))) %>% 
  # Select only records for administration
  filter(episodedatasource == "Administrations") %>%
  # bind with clinical
  inner_join(., clinical_data, 
          by = "patientid") %>% 
  arrange(patientid, episodedate)
```

```{r combine amount same drug one day}
combined_drugs <- drugs %>% 
  # Combined Multiple Administrations----
  # combined multiple amount of drug given the same day FCF86329BB40C F4E6EE1910940.May be 205 patients row like that
  group_by(patientid, linename, linenumber, linestartdate, lineenddate, episodedate,
           drugname, units, ismaintenancetherapy) %>%
  summarise_at(vars(route, amount), paste, collapse = ";") %>% # keep them in the data then do sum
  mutate(route = case_when(
    str_detect(route, ";")            ~ "Intravenous", # I checked that all the combined administration are IV
    TRUE                              ~ route
  )) %>% 
  separate(col= amount, paste("amount_", 1:10, sep=""), sep = ";", extra = "warn",
           fill = "right") %>%
  ungroup() %>% 
  mutate(across(starts_with("amount"), ~ na_if(., "NA"))) %>% 
  purrr::keep(~!all(is.na(.))) %>%
  mutate(across(starts_with("amount"), ~ as.numeric(.))) %>% 
  mutate(amount = rowSums(select(.,starts_with("amount_")), na.rm = TRUE)) %>%
  # Found ug, ml, Ea, and NA they are all good, but 
  # ug need conversion
  # the AUC are mostly correct (real mg) but are actual AUC when < at 10 so remove
  mutate(amount =  case_when(
    units == "ug"               ~ amount / 10, # I checked all of them
    units == "AUC" &
      amount < 10               ~ NA_real_,
    TRUE                        ~ amount
  ))# %>% 
  
  # mutate(drugname_type = case_when(
  #   str_detect(drugname, "platin")       ~ "platin",
  #   str_detect(drugname, "taxel")        ~ "taxel"
  # ))
```

```{r line coding}
therapy_line <- combined_drugs %>% 
  # bind again with clinical - was lost while summarizing
  inner_join(., clinical_data, 
          by = "patientid") %>% 
  arrange(patientid, episodedate) %>% 
  # Define Adjuvant, Neoadjuvant, chemo or surgery
  mutate(chemotherapy_type = case_when(
    # ismaintenancetherapy == "TRUE"    ~ "maintenance",
    episodedate <= surgerydate        ~ "Neoadjuvant", # F63ABD6AEB12C, F4F7B1C5DF24F intraperitoneal Carboplatin
    episodedate > surgerydate         ~ "Adjuvant",
    is.na(surgerydate) &
      !is.na(episodedate)             ~ "Chemotherapy only",
    !is.na(surgerydate) &
      is.na(episodedate)              ~ "Surgery only"
    )) %>% 
  mutate(chemotherapy_type = 
           factor(chemotherapy_type, levels = 
                    c("Neoadjuvant", "Adjuvant", "Chemotherapy only", "Surgery only"))) %>%
  group_by(patientid) %>% 
  mutate(had_neo = ifelse(str_detect(chemotherapy_type, "Neo"), "Yes", NA_character_)) %>% 
  mutate(had_adj = ifelse(str_detect(chemotherapy_type, "Adj"), "Yes", NA_character_)) %>% 
  fill(had_neo, had_adj, .direction = "updown") %>% 
  mutate(treatment_sequence = case_when(
    had_neo == "Yes" &
      had_adj == "Yes"                           ~ "neo + surg + adj",
    had_neo == "Yes" &
      is.na(had_adj)                             ~ "neo + surg",
    is.na(had_neo) &
      had_adj == "Yes"                           ~ "surg + adj",
    chemotherapy_type == "Chemotherapy only"     ~ "Chemotherapy only",
    chemotherapy_type == "Surgery only"          ~ "Surgery only"
  )) %>% 
  mutate(therapy = case_when(
    chemotherapy_type == "Neoadjuvant"           ~ "Upfront Chemo",
    chemotherapy_type == "Chemotherapy only"     ~ "Chemotherapy only",
    chemotherapy_type == "Surgery only"          ~ "Surgery only",
    is.na(had_neo) &
      had_adj == "Yes"                           ~ "Upfront Surgery"
  )) %>% 
  fill(therapy, .direction = "downup") %>% 
  
  # Redefine line number based on the original linenumber variable and the surgery date
  mutate(linenumber_n = dense_rank(interaction(linenumber, chemotherapy_type))) %>%  
  # Redefine line number based on the new linenumber variable and if a switch 
  # to maintenance is detected within the line
  group_by(patientid, linenumber_n, ismaintenancetherapy) %>% 
  mutate(maint_rank = row_number(ismaintenancetherapy),
         maint_rank = ifelse(maint_rank == 1, 1, 0)) %>% 
  group_by(patientid) %>% 
  mutate(linenumber_new = cumsum(maint_rank)) %>%  
  # F0000AD999ABF, F1C68CFAC2AF3, FBCF69031DFF8, F0040EA299CF0, FAACDC7205803,  FA019D2071321 no has big jump F95D860690A93 F0F1324B863A8
  select(patientid, linename, linenumber, linenumber_new, drugname, 
         episodedate, surgerydate, chemotherapy_type, everything()) %>% 
  ungroup() %>% 
  # Define line number restarting to 1 for each chemotherapy_type
  group_by(patientid, chemotherapy_type) %>% 
  mutate(linenumber_adj = dense_rank(linenumber_new)) %>% 
  ungroup() %>% 
  mutate(across(c("linenumber", "linenumber_new", "linenumber_adj"), as.factor)) %>% 
  # Redefine line dates
  group_by(patientid, linenumber_new) %>% 
  mutate(linestartdate = min(episodedate)) %>% 
  mutate(lineenddate = max(episodedate)) %>% 
  ungroup() %>% 
  select(-c(linenumber_n, maint_rank))
  
```

```{r cycle coding}
therapy_cycle <- therapy_line %>% 
  # Define cycle for each line
  # F003F2BEEDB37 need to change drugname pacli = pacli bp
  mutate(cycle_drugname = str_remove(drugname, " protein-bound")) %>%  
  # Need the number of time of the "major" drug is seen in the line
  group_by(patientid, linenumber_new, cycle_drugname) %>%
  mutate(drugname_count_perline = case_when(
           str_detect(drugname, "carboplatin|paclitaxel")     ~ n()
         )) %>%
  ungroup() %>% 
  arrange(patientid, episodedate, drugname) %>% 
  group_by(patientid, linenumber_new) %>%
  # Take the major drugname as a mark of new cycle start
  mutate(cycle_count_perline = min(drugname_count_perline, na.rm = TRUE)) %>%
  mutate(cycle_major_drugname = case_when(
    cycle_count_perline == drugname_count_perline &
      (cycle_drugname == "carboplatin" |
      cycle_drugname == "paclitaxel")                      ~ cycle_drugname,
    TRUE                                                   ~ NA_character_
  )) %>% 
  # select(-drugname_count_perline) %>% 
  # Code cycle number based on when major drug name appear again
  group_by(patientid, linenumber_new, drugname, cycle_major_drugname) %>%
  mutate(cycle_increment = row_number(cycle_major_drugname)) %>% # Look at F002DD2953889 inversed dose dense------------------
  # F01D908A013B7 weird dose dense

  # F003F2BEEDB37 change of dose dense 50% ok? ---------------------------------------------------------------
  
  arrange(patientid, episodedate, cycle_increment) %>% 
  group_by(patientid, linenumber_new) %>%
  fill(cycle_increment, .direction = "downup") %>%  # make sure I can do up for have one new drug compare to the linename FBB5186A15CD9 ok, FE593EDF5586A has a switched drugs will be removed
  group_by(patientid, chemotherapy_type, cycle_increment) %>% 
  # Code is_dose_dense to be 1 for the first drug in the cycle
  mutate(is_dose_dense = row_number(cycle_increment),
         is_dose_dense = ifelse(is_dose_dense == 1, 1, NA_real_)) %>% 
  group_by(patientid) %>% 
  mutate(total_cycle_increment = row_number(is_dose_dense)
         ) %>% 
  group_by(patientid, linenumber_adj) %>% 
  fill(total_cycle_increment, .direction = "downup") %>% 
  # cycle date
  group_by(patientid, linenumber_new, cycle_increment) %>% 
  mutate(cycle_start_date = min(episodedate)) %>% 
  
  # Look at dose dense
  # Code how many time a drug comes up in a cycle
  group_by(patientid, linenumber_new, cycle_increment, cycle_drugname) %>%  # weird dose dense F064D9EB733B3 F050B815FC126
  mutate(dose_dense = n()) %>% 
  mutate(dose_dense = max(dose_dense)) %>%  # too much cycle
  ungroup()
```

```{r target_auc and expected dose}
Treatment1 <- 
  # Merge with creatinine
  left_join(therapy_cycle, creatinine, by = "patientid") %>%
  mutate(interval_creat = abs(interval(start= creat_date, end= cycle_start_date)/                      
                          duration(n=1, unit="days"))) %>% 
  mutate(interval_creat = case_when(
    (therapy == "Upfront Surgery" &
       interval_creat < 31 &
       # creat_date < lineenddate &
       creat_date > surgerydate)                  ~ interval_creat,
    
    therapy == "Upfront Chemo" &
      (
        (chemotherapy_type == "Neoadjuvant" &
           interval_creat < 31 &
           creat_date < surgerydate) |
          (chemotherapy_type == "Adjuvant" &
             interval_creat < 31 &
             # creat_date < lineenddate &
             creat_date > surgerydate)
      )                                          ~ interval_creat,
    TRUE                                         ~ NA_real_
  )) %>%
  arrange(interval_creat) %>% 
  distinct(patientid, episodedate, drugname, amount, linenumber_new, cycle_count_perline, cycle_increment, 
           cycle_start_date, .keep_all = TRUE) %>% 
  
  # Merge with height
  left_join(. , height,  by = "patientid") %>%
  mutate(interval_height = abs(interval(start= height_date, end= cycle_start_date)/
           duration(n=1, unit="days"))) %>%
  arrange(interval_height) %>%
  distinct(patientid, episodedate, drugname, amount, linenumber_new, cycle_count_perline, cycle_increment,
           cycle_start_date, .keep_all = TRUE) %>%
  
  # Merge with weight
  left_join(. , weight, by = "patientid") %>%
  mutate(interval_weight = abs(interval(start= weight_date, end= cycle_start_date)/
                        duration(n=1, unit="days"))) %>%
  mutate(interval_weight = case_when(
    (therapy == "Upfront Surgery" &
       interval_weight < 31 &
       # weight_date < lineenddate &
       weight_date > surgerydate)                  ~ interval_weight,
    
    therapy == "Upfront Chemo" &
      (
        (chemotherapy_type == "Neoadjuvant" &
           interval_weight < 31 &
           weight_date < surgerydate) |
          (chemotherapy_type == "Adjuvant" &
             interval_weight < 31 &
             # weight_date < lineenddate &
             weight_date > surgerydate)
      )                                          ~ interval_weight,
    TRUE                                         ~ NA_real_
  )) %>%
  arrange(interval_weight) %>%
  distinct(patientid, episodedate, drugname, amount, linenumber_new, cycle_count_perline, cycle_increment,
         cycle_start_date, .keep_all = TRUE) %>%

  # Calculate ideal dody weight
  mutate(ideal_weight = case_when(
    height <= 1.524               ~ 45.5 + 2.3,
    height > 1.524                ~ 45.5 + (2.3 * (((height - 1.524) / 0.0254)))
  )) %>% 
  mutate(adjusted_weight = ((weight - ideal_weight) * 0.40) + ideal_weight
  ) %>% 
  # Calculate bmi
  mutate(bmi_at_dx = weight_at_dx / (height_at_dx * height_at_dx)) %>%
  mutate(bmi_cat = case_when(
    bmi_at_dx < 25                    ~ "Underweight and normal weight",
    bmi_at_dx >= 25 &
      bmi_at_dx < 30                  ~ "Overweight",
    bmi_at_dx >= 30                   ~ "Obese"
  )) %>%
  mutate(bmi_cat = factor(bmi_cat, levels = c("Underweight and normal weight", "Overweight", "Obese"))) %>%
  
  mutate(actual_bmi = weight / (height * height)) %>%
  mutate(actual_bmi_cat = case_when(
    actual_bmi < 25                    ~ "Underweight and normal weight",
    actual_bmi >= 25 &
      actual_bmi < 30                  ~ "Overweight",
    actual_bmi >= 30                   ~ "Obese"
  )) %>%
  mutate(actual_bmi_cat = factor(actual_bmi_cat, 
                                  levels = c("Underweight and normal weight", "Overweight", "Obese"))) %>%
  # select(patientid, weight, height, bmi_at_dx, ideal_weight, adjusted_weight, adjusted_bmi)
  # Calculate CrCl
  # inner_join(., clinical_data %>% select(-surgerydate),
  #            by = "patientid") %>% 
  mutate(CrCl = (
       (
    ((140 - ageatdx) * weight) /
    (72 * creatinine)
       ) *
    0.85)
  ) %>% 
  mutate(CrCl = case_when(
    CrCl > 125                        ~ 125,
    TRUE                              ~ CrCl
  )) %>% 
  mutate(adjusted_CrCl = case_when(
    actual_bmi >= 25                  ~ CrCl,
    actual_bmi < 25                   ~ (((140 - ageatdx) * adjusted_weight) / (72 * creatinine)) * 0.85
  )) %>% 
  mutate(adjusted_CrCl = case_when(
    adjusted_CrCl > 125               ~ 125,
    TRUE                              ~ adjusted_CrCl
  )) %>% 

  # Merge with body_surface_area
  left_join(., body_surface_area, by = "patientid") %>%
  mutate(interval_bsa = abs(interval(start= bsa_date, end= cycle_start_date)/
                          duration(n=1, unit="days"))) %>%
  mutate(interval_bsa = case_when(
    (therapy == "Upfront Surgery" &
       interval_bsa < 31 &
       # bsa_date < lineenddate &
       bsa_date > surgerydate)                  ~ interval_bsa,
    
    therapy == "Upfront Chemo" &
      (
        (chemotherapy_type == "Neoadjuvant" &
           interval_bsa < 31 &
           bsa_date < surgerydate) |
          (chemotherapy_type == "Adjuvant" &
             interval_bsa < 31 &
             # bsa_date < lineenddate &
             bsa_date > surgerydate)
      )                                          ~ interval_bsa,
    TRUE                                         ~ NA_real_
  )) %>%
  arrange(interval_bsa) %>%
  distinct(patientid, episodedate, drugname, amount, linenumber_new, cycle_count_perline, cycle_increment,
           cycle_start_date, .keep_all = TRUE) %>%
  # Calculate more bsa value with height and weight using Du Bois formula
  mutate(bsa_du_bois = 0.007184 * ((height*100)^0.725) * (weight^0.425)) %>% # get pretty close results 4269 patients result
  mutate(BSA = coalesce(BSA, bsa_du_bois)) %>%
  mutate(bsa_du_bois = 0.007184 * ((height_at_dx*100)^0.725) * (weight_at_dx^0.425))# %>% # get pretty close results 4269 patients result
  # mutate(bsa_at_dx = coalesce(bsa_at_dx, bsa_du_bois)) %>%
  # select(-bsa_du_bois) %>%

  # Merge with auc
  # left_join(., areaUC, by = c("patientid", "drugname")) %>%
  # mutate(interval_auc = abs(interval(start= auc_date, end= cycle_start_date)/ # use episode date to be more precise? No it's not better
  #                         duration(n=1, unit="days"))) %>% 
  # mutate(interval_auc = case_when(
  #   (therapy == "Upfront Surgery" &
  #      interval_auc < 31 &
  #      # auc_date < lineenddate &
  #      auc_date > surgerydate)                  ~ interval_auc,
  #   
  #   therapy == "Upfront Chemo" &
  #     (
  #       (chemotherapy_type == "Neoadjuvant" &
  #          interval_auc < 31 &
  #          auc_date < surgerydate) |
  #         (chemotherapy_type == "Adjuvant" &
  #            interval_auc < 31 &
  #            # auc_date < lineenddate &
  #            auc_date > surgerydate)
  #     )                                          ~ interval_auc,
  #   TRUE                                         ~ NA_real_
  # )) %>%
  # arrange(interval_auc) %>% 
  # distinct(patientid, episodedate, drugname, amount, linenumber_new, cycle_count_perline, cycle_increment, 
  #          cycle_start_date, .keep_all = TRUE) %>% 
  # 
  # # Calculate expected dose
  # mutate(expected_dose = case_when(
  #   drugname == "carboplatin"                 ~ target_auc * (CrCl + 25),
  #   drugname == "paclitaxel"                  ~ BSA * target_auc 
  #   # F19EBBFC60652 Can we fill target_auc? No depends of the type of cycle, or maybe by grouping by cycle type and drug
  # )) %>% 
  # mutate(expected_dose = case_when(
  #   expected_dose > 900 &
  #     target_auc == 6              ~ 900,
  #   expected_dose > 750 &
  #     target_auc == 5              ~ 750,
  #   TRUE                           ~ expected_dose
  # )) %>% 
  # mutate(adjusted_expected_dose = case_when(
  #   drugname == "carboplatin"                 ~ target_auc * (adjusted_CrCl + 25),
  #   drugname == "paclitaxel"                  ~ BSA * target_auc 
  #   # F19EBBFC60652 Can we fill target_auc? No depends of the type of cycle, or maybe by grouping by cycle type and drug
  # )) %>% 
  # mutate(adjusted_expected_dose = case_when(
  #   adjusted_expected_dose > 900 &
  #     target_auc == 6              ~ 900,
  #   adjusted_expected_dose > 750 &
  #     target_auc == 5              ~ 750,
  #   TRUE                           ~ adjusted_expected_dose
  # )) %>% 
  # group_by(patientid) %>%
  # mutate(first_treatment_date = case_when(
  #   str_detect(therapy, "Chemo")                      ~ min(episodedate),
  #   str_detect(therapy, "Surgery")                    ~ surgerydate,
  # )) %>% 
  # ungroup() %>% 
  # mutate(month_at_os_from_treatment = interval(start = first_treatment_date, end = followupdate)/
  #                  duration(n=1, units = "months")) %>% 
  # arrange(patientid, episodedate)

```

# Correlation BSA

```{r}
library(ggcorrplot)
Treatment1 <- Treatment1 %>% 
  filter(str_detect(patientid, paste(Frontline$patientid, collapse = "|"))) %>% 
  arrange(patientid, episodedate, drugname)

# coalesce(bsa_at_dx, bsa_du_bois)
a <- Treatment1 %>% 
  distinct(patientid, cycle_increment, .keep_all = TRUE) %>% 
  select(BSA, bsa_du_bois)
head(a)
# p.mat <- cor_pmat(a)
mat <- cor(a, use = "pairwise.complete.obs")
ggcorrplot(mat, hc.order = TRUE, method = "square",
           insig = "blank", # Leave blank on no significant coefficient
           type = "lower",
           lab = TRUE,
           title = "Correlation",
           show.legend = TRUE, legend.title = "Correlation", show.diag = TRUE,
           lab_col = "darkblue", lab_size = 3,
           sig.level = 0.05, #insig = c("pch", "blank"), pch = 4, pch.col = "black", pch.cex = 10,
           tl.cex = 10,
           tl.srt = 90,
           # digits = 1,
           outline.color = "white",
  ggtheme = ggplot2::theme_gray,
  colors = c("blue", "white", "#E46726")
)


a <-Treatment1 %>% 
  distinct(patientid, .keep_all = TRUE) %>% 
  select(BSA, bsa_du_bois)
head(a)
mat <- cor(a, use = "pairwise.complete.obs")
ggcorrplot(mat, hc.order = TRUE, method = "square",
           insig = "blank", # Leave blank on no significant coefficient
           type = "lower",
           lab = TRUE,
           title = "Correlation",
           show.legend = TRUE, legend.title = "Correlation", show.diag = TRUE,
           lab_col = "darkblue", lab_size = 3,
           sig.level = 0.05, #insig = c("pch", "blank"), pch = 4, pch.col = "black", pch.cex = 10,
           tl.cex = 10,
           tl.srt = 90,
           # digits = 1,
           outline.color = "white",
  ggtheme = ggplot2::theme_gray,
  colors = c("blue", "white", "#E46726")
)
# mat <- matrix(c(1,2,3), nrow = 1, ncol = 3, byrow = TRUE,
#                dimnames = list(c("row1"),
#                                c("C.1", "C.2", "C.3")))
# cor(mat)
```









