---
title: "Flatiron analysis"
author: "Christelle Colin-Leitzinger"
date: "3/17/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: flatly
    highlight: pygments
    df_print: paged
---

<style type="text/css">
.figure {
   margin-top: 25px;
   <!-- margin-bottom: 100px; -->
}

table {
    margin-top: 25px;
    <!-- margin-bottom: 100px !important; -->
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
options(gtsummary.print_engine = "gt")
options(gtsummary.as_gt.addl_cmds = "gt::tab_options(table.font.size = 14, data_row.padding = gt::px(1))")
```

# Analysis
***
<br>

```{r library, include=FALSE}
library(drake)
library(tidyverse)
library(data.table)
library(lubridate)
library(ggplot2)
library(gtsummary)
library(survminer)
library(survival)
```

```{r loadd}
loadd(clinical_data, vitals, drugs, auc, creatinine)
```

## 
